name: "📸 Regenerate PNG"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - resume.pdf
jobs:
  regenerate-png:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Install deps
        run: |
          sudo apt-get install poppler-utils --no-install-recommends

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: PDF to png
        run: pdftoppm -png -singlefile resume.pdf resume
        
      - name: Upload PNG file
        uses: actions/upload-artifact@v3
        with:
          name: PNG
          path: resume.png
      - name: Commit and Push new file
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "add PDF file"
          git push
